name: Pipeline Testing

on:
  push:
    branches: [quick-book-lucy]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Root Dependencies
        run: npm install

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
        

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
        

  backend:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Unit Tests
        run: |
          cd backend
          npm test
        

  frontend:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Start Frontend Server
        run: |
          cd frontend
          npm run dev -- --host 0.0.0.0 > ../frontend.log 2>&1 &
        
        env:
          CI: true
          VITE_API_BASE_URL: https://quickbook-testing.onrender.com

      - name: Wait On Frontend
        run: npx wait-on http://localhost:5173 --timeout 12000

      - name: Show Frontend Log
        if: always()
        run: cat frontend.log

  cypress:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Start Frontend Server
        run: npm run dev -- --host 0.0.0.0 &
        working-directory: frontend
        env:
          VITE_API_BASE_URL: https://quickbook-testing.onrender.com

      - name: Wait On Frontend
        run: npx wait-on http://localhost:5173 --timeout 120000

      - name: Install Cypress
        run: npx cypress install

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress Tests
        run: npx cypress run --browser electron
