name: Pipeline Test Suite

on: 
  push:
    branches: [task-one]

jobs:
  jobOne:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install node 
        uses: actions/setup-node@v4
        with: 
          node-version: 22

      - name: install root dependencies 
        run:  npm install  
        

